server:
  port: 9002
  shutdown: graceful # graceful shutdown
  netty:
    connection-timeout: 2000 # 2 seconds
    idle-timeout: 15000 # 15 seconds

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"

  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2000 # 2 seconds
      initial-size: 5 # initial size of the connection pool
      max-size: 10 # maximum size of the connection pool
  flyway:
    driver-class-name:  org.postgresql.Driver
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order
  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched # Destination topic/exchange for the incoming messages
          group: ${spring.application.name} # Consuming messages from <destination>.<group> queue
          content-type: application/json
          consumer:
            use-native-decoding: false # disable native decoding to receive messages as byte arrays for manual
        acceptOrder-out-0:
          destination: order-accepted # Destination topic/exchange for the outgoing messages which will route messages to bound queues
      rabbit:
        bindings:
          acceptOrder-out-0:
            producer:
              transacted: true # enable transactions for the producer to ensure message delivery

    config:
      enabled: true
      uri: http://localhost:8888 # URL of the config server
      request-connect-timeout: 5000 # 5 seconds
      request-read-timeout: 5000 # 5 seconds
      fail-fast: false # fail fast if the config server is not reachable
      retry:
        max-attempts: 3 # maximum number of retry attempts
        initial-interval: 1000 # initial interval between retries in milliseconds
        max-interval: 2000 # maximum interval between retries in milliseconds
        multiplier: 1.5 # multiplier for the interval between retries
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

polar:
  catalog-service-uri: http://localhost:8082